
[build]
# Path relative to the root of the repository
# Leaving this for potential future use 
# publish = "docs/site"
# base = "docs"

# Branch deploy context:
# All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
[context.branch-deploy]
  command = "make staging"

# Path relative to the "base" directory
command = "sh -x scripts/netlify.sh"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"